name: routine_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  build_runner: ^2.4.6
  flutter:
    sdk: flutter
  isar: ^3.1.0+1
  isar_generator: ^3.1.0+1
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
